import { defineStore } from "pinia";

export const useTodoStore = defineStore('todo', {
    state: () => ({
        Promotion: [
            {
              text: "Everydat Fresh & Clean With Our Products",
              img: "./src/assets/img/Onion.png",
              color: "#F0E8D5",
              btn: "#3BB77E",
              txtbtn: "Shop Now",
            },
            {
              text: "Make Your Breakfast Healthy and Easy",
              img: "./src/assets/img/Milk.png",
              color: "#F3E8E8",
              btn: "#3BB77E",
              txtbtn: "Shop Now",
            },
            {
              text: "The Best Organic Products Online",
              img: "./src/assets/img/Fruits.png",
              color: "#E7EAF3",
              btn: "#FDC040",
              txtbtn: "Shop Now",
            }
          ],
          Category: [
            {
              color:"#F2FCE4",
              img: "./src/assets/img/Burger.png",
              title:"Burger",
              item:"10 items",
            },
            {
              color:"#FFFCEB",
              img: "./src/assets/img/Peach.png",
              title:"Peach",
              item:"12 items",
            },
            {
              color:"#ECFFEC",
              img: "./src/assets/img/Kiwi.png",
              title:"Organic Kiwi",
              item:"13 items",
            },
            {
              color:"#FEEFEA",
              img: "./src/assets/img/Apple.png",
              title:"Red Apple",
              item:"50 items",
            },
            {
              color:"#FFF3EB",
              img: "./src/assets/img/Snack.png",
              title:"Snack",
              item:"30 items",
            },
            {
              color:"#FFF3FF",
              img: "./src/assets/img/Plum.png",
              title:"Black Plum",
              item:"20 items",
            },
            {
              color:"#F2FCE4",
              img: "./src/assets/img/Cabbage.png",
              title:"Vegtables",
              item:"100 items",
            },
            {
              color:"#FFFCEB",
              img: "./src/assets/img/Headphone.png",
              title:"Headphone",
              item:"10 items",
            },
            {
              color:"#F2FCE4",
              img: "./src/assets/img/CM.png",
              title:"Cake & Milk",
              item:" 40 items",
            },
            {
              color:"#FFF3FF",
              img: "./src/assets/img/Orange.png",
              title:"Orange",
              item:" 60 items",
            }
          ],
          Products: [
            {
              id: 1,
              tag: "-17%",
              tagBg: "#3BB77E",
              image: "./src/assets/img/p1.png",
              category: 3,
              name: "Seeds of Change Organic Quinoa, Brown, & Red Rice",
              rate: 4.0,
              description: "500 gram",
              sellPrice: "2.00",
              discountPercentage: 17,
              discountPrice: "3.00",
            },
            {
              id: 2,
              tag: "Hot",
              tagBg: "#FD6E6E",
              image: "./src/assets/img/p2.png",
              category: 3,
              name: "All Natural Italian-Style Chicken Meatballs",
              rate: 4.0,
              description: "500 gram",
              sellPrice: "2.00",
              discountPercentage: 17,
              discountPrice: "3.00",
            },
            {
              id: 3,
              tag: "Sale",
              tagBg: "#FDC040",
              image: "./src/assets/img/p3.png",
              category: 3,
              name: "Angie’s Boomchickapop Sweet & Salty Kettle Corn",
              rate: 4.0,
              description: "500 gram",
              sellPrice: "2.00",
              discountPercentage: 17,
              discountPrice: "3.00",
            },
            {
              id: 4,
              tag: "",
              tagBg: "",
              image: "./src/assets/img/p4.png",
              category: 3,
              name: "Foster Farms Takeout Crispy Classic Buffalo Wings",
              rate: 4.0,
              description: "500 gram",
              sellPrice: "2.00",
              discountPercentage: 17,
              discountPrice: "3.00",
            },
            {
              id: 5,
              tag: "",
              tagBg: "",
              image: "./src/assets/img/p5.png",
              category: 3,
              name: "Blue Diamond Almonds Lightly Salted Vegetables",
              rate: 4.0,
              description: "500 gram",
              sellPrice: "2.00",
              discountPercentage: 17,
              discountPrice: "3.00",
            },
            {
              id: 6,
              tag: "",
              tagBg: "",
              image: "./src/assets/img/p6.png",
              category: 3,
              name: "Chobani Complete Vanilla Greek Yogurt",
              rate: 4.0,
              description: "500 gram",
              sellPrice: "2.00",
              discountPercentage: 17,
              discountPrice: "3.00",
            },
            {
              id: 7,
              tag: "Sale",
              tagBg: "#FDC040",
              image: "./src/assets/img/p7.png",
              category: 3,
              name: "Canada Dry Ginger Ale – 2 L Bottle - 200ml - 400g",
              rate: 4.0,
              description: "500 gram",
              sellPrice: "2.00",
              discountPercentage: 17,
              discountPrice: "3.00",
            },
            {
              id: 8,
              tag: "",
              tagBg: "",
              image: "./src/assets/img/p8.png",
              category: 3,
              name: "Encore Seafoods Stuffed Alaskan Salmon",
              rate: 4.0,
              description: "500 gram",
              sellPrice: "2.00",
              discountPercentage: 17,
              discountPrice: "3.00",
            },
            {
              id: 9,
              tag: "",
              tagBg: "",
              image: "./src/assets/img/p9.png",
              category: 3,
              name: "Gorton’s Beer Battered Fish Fillets with soft paper",
              rate: 4.0,
              description: "500 gram",
              sellPrice: "2.00",
              discountPercentage: 17,
              discountPrice: "3.00",
            },
            {
              id: 1,
              tag: "Hot",
              tagBg: "#FD6E6E",
              image: "./src/assets/img/p10.png",
              category: 3,
              name: "Haagen-Dazs Caramel Cone Ice Cream Ketchup",
              rate: 4.0,
              description: "500 gram",
              sellPrice: "2.00",
              discountPercentage: 17,
              discountPrice: "3.00",
            },
          ],
    })
})